### ISSUE TITLE
No Home Page

### ISSUE THREAD

**Issue by LDwhoRU** [QUT-Motorsport/QUTMS_VehicleSim#1]
Live Telemetry in the future will be the home page, however until then, a template should be made for the Live Telemetry page to show what it should like eventually. Currently home page is upload for Plot Mass

**Comment by J-Hoskin** [comment]
Telemetry Parameters:

- Ground speed (km/h)
- Throttle and brake pos (% - bars)
- Motor RPM (rpm)
- Steering angle (degrees)
- Current charge %
- CG Accelation long and lat

**Comment by LDwhoRU** [comment]
Don't do Motor RPM, its wheel RPM

The max wheel RPM is 1191, so id make all lights display when the wheel RPM is over 1000.

**Comment by LDwhoRU** [comment]
Heres a converter for Speed to Wheel RPM. The radius (Wheel Radius) is 10 inches.

http://www.endmemo.com/physics/rpmlinear.php

On the bottom of the page you will find the formula, which you will need to implement.

**Comment by J-Hoskin** [comment]
http://naimagon.com/sap-mclaren-race-dashboard/

**Comment by LDwhoRU** [comment]
Solution for Speedometer

https://stackoverflow.com/questions/14222138/css-progress-circle

http://jsfiddle.net/andsens/mLA7X/
