### ISSUE TITLE
Implement User Auth

### ISSUE THREAD

**Issue by LDwhoRU** [QUT-Motorsport/QUTMS_VehicleSim#16]
Need user auth for custom environment settings from user to user. This can simply be done with Flask-Login.

- [x] Ability to register
- [x] Ability to login
- [x] Disable access to view or delete analysis instances from other users
- [x] Logout
- [x] Change password

**Comment by jimcinbrisbane** [comment]
**What ability does the admin account have?**
Current Assumption:
Deleting data, User Profiles etc?

**What kind of information does the user profile provide?**
Current Assumption:
changing username, password, company, profile picture and role..?

**Comment by jimcinbrisbane** [comment]
To change the password, I was thinking to handle the process we can:
1. verify their email or phone number
2.send a reset password request to the admin => admin approve => reset password successfully, If so, what information do they need to provide?

**Comment by LDwhoRU** [comment]
Do you reckon it would be easier to just add email auth traditionally from the register page, and record the users email, and then just install reset password behaviour from that? That seems like a more straightforward & simple solution than getting admins involved.

**Comment by jimcinbrisbane** [comment]
that'll work

**Comment by LDwhoRU** [comment]
No worries. Don't worry about implementing a system that will require you to validate your email address prior tho, given the low priority security takes in this application. User profiles are merely just to declutter the interface when deployed + Add optional user settings from user to user.
