### ISSUE TITLE
Colour sorted GG Diagram

### ISSUE THREAD

**Issue by LDwhoRU** [QUT-Motorsport/QUTMS_VehicleSim#9]
Claude wrote a paper on Asymmetric setups and how GG Diagrams are categorized and seperate in order to refine asymmetric setups. Implement similar colouring scheme with raw output of values in pre-defined ranges.

Paper can be found here:
https://optimumg.com/characterising-tracks-for-set-up-solutions/

**Comment by LDwhoRU** [comment]
Logic looks good. Output looks good. Missing boxes, but closed as eventually it will be ported to config app (And all the logic will be re used). If you have time is there anyway to make slightly smaller plots? Probably just a matplotlib parameter you need to pass, but other than that looks good!

**Comment by antfc** [comment]
If by boxes you mean the boxes around each section, it's just commented out on line 208 in plotting.py It's called gg_boxes(). Otherwise the size of the plots has been changed using markersize
